### ISSUE TITLE
Investigate react frontend

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp-admin#20]
https://github.com/marmelab/admin-on-rest

**Comment by Eduard90** [comment]
It's very interesting. I think it's good idea :-)

**Comment by wolendranh** [comment]
@jettify should it be as an option for admin or replacement?

**Comment by jettify** [comment]
Frontend completely decoupled from server side, basically aiohttp-admin nothing more than REST api. As for frontend, ng-admin (angular bases https://github.com/marmelab/ng-admin) has simple way to create admin UI based on REST api, nothing stops us to use react based similar library, for instance https://github.com/marmelab/admin-on-rest  . It is relatively easy to support both.

Right now there is no way to do create UI automatically, user expected to know ng-admin and create simple js config on his own, I have semi automatic solution for ng-admin, like base on models bootstrap js config, but this is not final thing and subject of change. 

React is completely other thing and all automatic UI creation should be implemented separately, but REST api part could be reused.

**Comment by jettify** [comment]
@thenx are you using `ng-admin`? curious about your opinion `ng-admin` vs `admin-on-rest`

**Comment by thenx** [comment]
I'm currently perfectly fine with minimalistic `ng-admin`, but `admin-on-rest` looks prettier on the video. I think i'd give it a try if it worked out of the box.
