### ISSUE TITLE
Unclear how to install aiohttp_admin in another project

### ISSUE THREAD

**Issue by gyermolenko** [aio-libs/aiohttp-admin#331]
I tried to do `pip install aiohttp-admin` and `pip install aiohttp_admin` - and got a `Could not find a version that satisfies the requirement` message from pip.

The best way to install it I found so far is `pip install -e .`
Is there a better way to include `aiohttp_admin` into user's project?

**Comment by asvetlov** [comment]
@jettify ?

**Comment by jettify** [comment]
I do not think I deployed it to pypi, can do tonight
