### ISSUE TITLE
Migrate to react and admin-on-rest

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp-admin#359]
There is plans to migrate to react with  `admin-on-rest` [1] UI framework since `ng-admin` uses outdated angular.

[1] https://github.com/marmelab/admin-on-rest

- [ ] edit, view forms
- [ ] filters
- [ ] relations between tables
- [ ] more robust and customizable fields
- [ ] drop `ng-admin` stuff

**Comment by not-mms** [comment]
what about [react-admin](https://github.com/marmelab/react-admin) guys?

**Comment by Arfey** [comment]
We started to test [react-admin](https://github.com/aio-libs/aiohttp_admin/tree/master/demos/blog_react).

You can use `aiohttp_admin` as rest api and `react-admin` as view without any problems.
