### ISSUE TITLE
when there is an error, Im automatically logged out of admin.

### ISSUE THREAD

**Issue by japrogramer** [aio-libs/aiohttp-admin#390]
Every time there is an error in my request to the backend
I am logged out of admin. using master branch.

**Comment by Arfey** [comment]
Do u use this example https://github.com/aio-libs/aiohttp_admin/tree/master/demos/blog_react?

**Comment by japrogramer** [comment]
I am using that pattern

**Comment by Arfey** [comment]
Sorry, but it's not ready yet. Use examples from a stable release.
https://github.com/aio-libs/aiohttp_admin/tree/master/demos/blog

**Comment by japrogramer** [comment]
Hmm I didn't like how those examples where written,
I'll stick to this for now :(

**Comment by Arfey** [comment]
I recommend using a stable version because it works fine and has more features than the new version.
