### ISSUE TITLE
What i need to do after installing aiohttp_admin??

### ISSUE THREAD

**Issue by VladLazoryk** [aio-libs/aiohttp-admin#445]
I have already installed aiohttp_admin but there arent anything in the documentation what to do after installing. What i need to import and where i need to do it. Please can you write it in the documentation.

**Comment by Arfey** [comment]
A quick solution for u it's to look at the [demos](https://github.com/aio-libs/aiohttp_admin/tree/master/demos). There u can see how to use aiohttp_admin.
